### ISSUE TITLE
Calcium H& K box

### ISSUE THREAD

**Issue by dparkins** [Samreay/Marz#112]
In the 'Detailed view', at the bottom of the screen you have three sub-boxes for the lines relating to  [OII], H-beta and [OIII], and H-lapha [NII] and [SII]. I often use the singly-ionized Calcium HK absorption doublet (H is 3968 angstrom and K is 3933 angstroms). This double feature is often more useful than the emission lines for redshifting. Would it be possible to have this box instead of one of the emission feature boxes, for some spectra?

**Comment by Samreay** [comment]
Turns out I will get to this tonight. There is an HK box already, just lower priority than the others. However, I've decreased min box width from 400 to 350 pixels, so if it wasnt displaying before, could I check to see if it is displaying for you now?

**Comment by dparkins** [comment]
Yes, it's fine. It seems to be more dynamic, sometimes making a box for the magnesium line, sodium absorption, or silicon lines. Looks great!

**Comment by Samreay** [comment]
Awesome. Thanks for giving it a check over.
