### ISSUE TITLE
Enter initials

### ISSUE THREAD

**Issue by tamarastro** [Samreay/Marz#113]
Hi Sam, 
When I run Marz with the "Auto-assign QOP" option on, I get what may be 400 requests for my initials to be entered....  It flickers and looks like it is trying to put up a new screen many times per second. After the processing has finished I was able to enter initials and download the results, but it still keeps the initials window open and won't let me cancel it.  I feel it may be wanting me to cancel it 400 times...
![temp](https://cloud.githubusercontent.com/assets/7409521/9101382/6954a8ac-3c29-11e5-8c75-4a4fe9dfd86c.png)
Tam

**Comment by Samreay** [comment]
So the requests pop up before it tries to download the results?
