### ISSUE TITLE
How can we cite or reference this software?

### ISSUE THREAD

**Issue by dparkins** [Samreay/Marz#115]
If we use this software for science, and want to cite or refer to it, beyond the hyperlink to the github page, how can we do so? Is there a Hinton et al (2016) in preparation?

**Comment by Samreay** [comment]
There is a Hinton et al in prep, hoping to have it out soon^TM once I get the final round of feedback from the other coauthors.

**Comment by Samreay** [comment]
Updated welcome page with link to documentation.
