### ISSUE TITLE
side panel unreadable

### ISSUE THREAD

**Issue by rainwoodman** [Samreay/Marz#131]
See attached figure.

I use a minimal font-size in the browser. Consider allow dragging the panel splitter? 

![screenshot from 2016-04-05 10-21-23](https://cloud.githubusercontent.com/assets/138060/14291383/35e8bac2-fb18-11e5-8473-733ede595ff7.png)

**Comment by Samreay** [comment]
Hi Yu,

Seems like a fair bit of the CSS isn't working properly on your browser. This is Ubuntu/Firefox combo I assume?

The sidebar wraps, but even worse the top bars also wrap for some reason.

From your comment, it appears you might have changed the normal rendering behaviour of FF, if so, would you be able to let me know how, so I can reproduce it and make sure the UI behaves as expected.

In the meantime I've increased the sidebar spacing until we can get reproduction going.
Cheers

**Comment by rainwoodman** [comment]
Thanks for the fix!

**Comment by Samreay** [comment]
Apologies for the delay! I left the issue and planned to get back to it when I heard back from you, and only realised it was still open when someone else opened a different issue! If there are still issues, please let me know.
