### ISSUE TITLE
Issue with some templates

### ISSUE THREAD

**Issue by saimn** [Samreay/Marz#135]
I have several templates (for LyA, CIII) that Marz refuse to process. It doesn't show the cross-correlation and the template, though I can still manually click on the line and then I get the correct z and see the template.

So after diving in the code, I don't understand the second part of `TemplateManager.prototype.shiftTemplate` and the relation between the redshift of the template, z_start, z_end, and the startZIndex/endZIndex you are computing (and maybe also globalConfig.startPower, globalConfig.endPower).

Let's take an example: I have a LyA template, where:

```
    "start_lambda": 900.0,
    "end_lambda": 1895.769591008408,
    "redshift": 0.0,
    "z_start": 2.7,
    "z_end": 6.4,
    "shift": false,
```

And

```
globalConfig.startPower = 2.8;
globalConfig.endPower = 4.0;
globalConfig.arraySize = 32768;
```

When I look at `shiftTemplate`, it computes `t.startZIndex = 31900` and `t.endZIndex = null`, which seems not good. If I use only these templates, I get many errors in `coalesceResults` because the templates `.peaks` is empty.
Is there some setting somewhere that should be adjusted for highz templates, or other ideas on what to look at ?

**Comment by Samreay** [comment]
Ah right, so what is happening is that all templates get rebinned to a
log-linear wavelength (array size 2^32) to far xcorr. So what you would
need to do is increase the `endPower` to a large enough number (I would try
4.2 and go up in 0,1 increments until it works) that the redshift range you
want is captured by the array.

Given the high redshift, it might be useful to increase the arraySize by a
factor of two, to make sure you dont lose precision with lower redshift
templates (however you may not need to do this, I have not tested the
impact of precision, array size and redshift for such high redshift ranges).

Apologies for the hassle getting this to work!

**Comment by saimn** [comment]
Ah thanks, I tried several things but didn't go far enough for `endPower`: with 4.6 it is working ! I also increased `arraySize`, thanks for the advice.
Don't apology, your software is really good (particularly with these highz templates now working) ! :clap: 
It is normal to have a few adaptations to make for different data.
