### ISSUE TITLE
Handle commas in comments

### ISSUE THREAD

**Issue by saimn** [Samreay/Marz#139]
Currently using commas in comments will break.
For the export, it would require to enclose the comment field in quotes, which is easy to do.
But then, this should also be handled in the import of .mz files. Instead of re-coding this, there is a library which seems nice (http://papaparse.com/). It could also be a better way to handle the types conversion (http://papaparse.com/#type-conversion), if it works ...

**Comment by Samreay** [comment]
Ah yes, commas. I believe I never implemented this as OzDES specifications
state that no commas will be found in the comments (as the comment field is
used by OzDES to record the object type). However, obviously not a robust
assumption for other uses! I'll see if I can integrate papaparse or a
similar library then. I'll try and jump on it today too, so stay tuned!

**Comment by saimn** [comment]
Ok great ! Actually I found a replace is done currently, but JavaScript is so funny that it replaces only the first occurrence: 

```
> spectra.getComment()
"hello, commas,, !!"
> spectra.getComment().replace(","," ")
"hello  commas,, !!"
```

So as a workaround, current code can be replaced with:

```
> spectra.getComment().split(',').join(';')
"hello; commas;; !!"
```

**Comment by Samreay** [comment]
It should work if the replace becomes a replaceAll.

So doing it this way would remove commas from the comments and stop them
being serialised. Is this acceptable, or would commas be important for your
purposes to have in comments?

**Comment by saimn** [comment]
Commas are not really important if they are correctly replaced with another separator. Of course it would be nice to handle this correctly, and using Papaparse may also be a better to parse columns with the good type, but it depends also on the effort that is needed to replace the current code. Maybe it's not worth it.

**Comment by Samreay** [comment]
I'll see how the integration of papaparse goes then. I'm heading into work in about half an hour, so hopefully will have some results before you sign off for the day!

**Comment by saimn** [comment]
Ok thanks :)

**Comment by Samreay** [comment]
So I've throw PapaParse into Marz locally to see how it does, and its bringing back memories of why I ended up with the nasty manual version at the moment. Namely, the requirement from OzDES weren't a CSV file, but a human readable CSV file (space padding, etc), which generally plays havoc with csv readers that either don't have a trim feature, or get confused about numeric types when surrounded with spaces.

PapaParse isn't good with handling the spaces, but they could be regexed out prior to passing to PapaParse. The main issue atm with PapaParse is that it can't handle extra commas in CSVs either, even when they occur inside double quotes in a string field. 

Ill have a look into jquery-csv and see if this might be a better replacement.

**Comment by Samreay** [comment]
Hmm, so jquery-csv seems like it can handle double quotes just fine, but doesn't have the features of PapaParse like headers and ignoring comments. Where is the web version of `np.genfromtxt` when you need it?

**Comment by saimn** [comment]
Too bad PapaParse doesn't handle quoted strings, it looked like a nice and well documented library. So, now that commas are well replaced, I think we can stop there and close this issue. Thanks a lot for trying to find an alternative !
And btw it is nice and helpful to have a readable output file.

**Comment by Samreay** [comment]
Sounds like a plan. If there are any other issues with parsing or loading files please just let me know - that area of the code is probably the least contribution friendly due to the dirty from-scratch implementation. Same applies for the plotting code, which is a monstrous section of directives.js - just let me know and Ill get on it!

Cheers

**Comment by saimn** [comment]
Ok, thanks for your help !
