### ISSUE TITLE
Issue with some templates, z = NaN

### ISSUE THREAD

**Issue by saimn** [Samreay/Marz#140]
With some of our templates (the stellar ones but not sure if/how it is related), I get a NaN redshift and Infinity correlation. It was a good mean to go more in detail into the algorithm ;-), and I found that in these cases only one correlation peak is found in `rmsNormalisePeaks`, which leads to a division by zero:

```
function rmsNormalisePeaks(final) {
    var peaks = getPeaks(final).value;
    var rms = getStdDev(peaks);
    for (var i = 0; i < final.length; i++) {
        final[i] /= rms;
    }
}
```

Testing that `rms > 0` solves the issue, not sure if it is the best way ?

**Comment by Samreay** [comment]
Hi Simon,

Interesting, what an unusual object to only have one peak within that range.

So in terms of adding `rms > 0`, I worry that this would overweight stars in which there was only a single peak. It is however, better to have misweighted results than NaN results!

You mentioned that this was with some of your own templates, so I would make sure that your `z_end` range was high enough. In fact, stars the whole reason why both `z_end` and `z_end2` exist - `z_end` was supposed to be large enough to get multiple peaks for normalisation, and `z_end2` then restricted the choice of possible peaks within a more physically motivated range. Without `z_end2` declared, `z_end` defines both the normalisation range and physical redshift range. For the templates you are having issue with, I would try to ensure that the `z_end` redshift range is sufficient to get multiple peaks. If that does not help, or is already done, let me know!

I'll also add an `rms > 0` into the code base.

**Comment by saimn** [comment]
Hi Samuel,
Thanks for your answer. I think I got the same error with your templates, but I have to check again this and the use of `z_end2`.
