### ISSUE TITLE
Marz provides no feedback when loading results from previous versions in.

### ISSUE THREAD

**Issue by marlageha** [Samreay/Marz#142]
I am using marz for a recent AAT-2dF run and am extremely impressed with this interface.   very well done.   However, I am having trouble uploading a results file and seeing my previous work.    I have followed the directions to first upload a results file (re-named from the saved .mz file to .csv) and then the corresponding fits file.   I am unable to see the previous results.   I've tried this in 2 browsers (firefox and chrome) and several different pointings.   Thanks.

**Comment by Samreay** [comment]
Does the issue still happen if you do not rename the file? Marz searches for input files to have the .mz extension and uses this when loading in files.

**Comment by marlageha** [comment]
At first I tried the .mz files, but when this didn't work I changed the extension to .mz.   When I upload the .mz file (or csv), it says "Have loaded results, Drop in fits file".   I drop in the fits file and it processes as usual, but the QOPs remain grey and set to zero.

**Comment by Samreay** [comment]
Ill take a look! Would you be able to attach to the issue both the mz file and the fits files and I'll try on my end and see whats going on?

**Comment by marlageha** [comment]
Thanks!   I sent them by email as github wasn't sure what to do with a .mz file.   much appreciated.

**Comment by Samreay** [comment]
Hmm, I havent received anything yet, and Im about to head off for the night, so hopefully they'll be in my inbox in the morning and Ill have it all sorted by lunch time.

**Comment by marlageha** [comment]
Here is a second set of files:
https://www.dropbox.com/s/v1fp6kayqqkt04w/AnaK2016_1_MG.mz?dl=0
https://www.dropbox.com/s/0n32bu5ge5ulibo/AnaK2016_1.fits?dl=0

**Comment by Samreay** [comment]
Aha, I see whats happening. The results file was generated when Marz was v1.2.7, and yesterday I updated it to v1.2.8 (cosmetic change) based on some feedback from ChrisL. Marz at the moment does not load results from previous versions, in case there is some change in the matching algorithm behind the scenes between version changes. However, this is definitely not communicated well, and I will think of some smarter behaviour for Marz going forward.

At the moment, to load your results in, simply change your .mz file so it has version 1.2.8 and try it again, it should work!

Ill keep this issue open and put any changes I make in here. Thanks for letting me know!

**Comment by marlageha** [comment]
Great!   This changed worked, thanks for your quick reply.

**Comment by Samreay** [comment]
Okay, so I've got a change that should make this issue happen far less often in the future, however it is going to break the current changes. As such, can you let me know when you've finished your current file and I will push out the changes, so that Im not disrupting your work.

**Comment by marlageha** [comment]
Please go ahead and push the changes.   Any sessions I am in right now aren't important.  thanks.

**Comment by marlageha** [comment]
Just to clarify, will the updates allow backward compatibility?

**Comment by Samreay** [comment]
Youll still be able to drag in .mz files (doing the same version trick), but refreshing the page will clear results. Its just the key I use to store things internally has changed.

**Comment by marlageha** [comment]
Sorry to reopen, but I am now unable to load any results files and am getting the error "Warning results file doesn't match current marz version".   I have tried editing my results file to have version 1.2.8 and 1.3.0 with the same results.

**Comment by Samreay** [comment]
Apologies, I see where I went wrong. Hopefully now it works. Sorry for the hassle!
