### ISSUE TITLE
"Previous" shotcut for best fit templates

### ISSUE THREAD

**Issue by nataliaeire** [Samreay/Marz#146]
We can use "o" to jump to the next best fit template in the detailed view. It would be very helpful to be able to jump backwards using the keyboard as well. I believe "i" isn't use for anything else, and it would be convenient to have forwards and backwards next to each other.

**Comment by Samreay** [comment]
Hey Nat, sure thing. Ill jump on it now for you :)

**Comment by Samreay** [comment]
So that should be done now, refresh and make sure Marz is now v1.3.7 (hover mouse of marz logo in top right for version). Good to hear from you though. Hope you are well :)
