### ISSUE TITLE
Air or Vacuum? 

### ISSUE THREAD

**Issue by jessicawerk** [Samreay/Marz#156]
Hello Sam! Thank you for making such a wonderful, easy-to-use web tool for redshift fitting. 
I've been using the web browser version to find redshifts for a sample of quasars and it generally works very well, but I've recently become confused about whether your linelists are in vacuum or air. All the documentation I've found says MARZ works on air wavelengths, but it seems like your linelist is actually in vacuum (e.g. your Halpha is 6564.6; if it were using air it would be 6562.8). It doesn't seem like there is a shift being done on my wavelengths. Can you verify one way or the other? I can easily convert my wavelength array to be in vacuum. It makes a difference! 
Thanks a lot. 
- Jess

**Comment by Samreay** [comment]
Hey Jess, so the TLDR is that everything in Marz should be done in vacuum wavelengths, and it will convert from air to vacuum (both templates and input fits file spectra) based upon some flags.

For input fits files, it checks to see if there is a `VACUUM` key in the fits header, and is null (unset), or 0, "F" or false, it will then shift the input wavelengths (which also are refined in the headers as either linear or log) from air to vacuum.

The code for this, if you're curious, is line 598 of `classes.js` :)

**Comment by jessicawerk** [comment]
Brilliant! Thank you so much for the response! :)
