### ISSUE TITLE
Vacuum/air wavelengths

### ISSUE THREAD

**Issue by tansb** [Samreay/Marz#157]
Hi Sam,

I've been using Marz to measure redshifts for a collection of VLT/XShooter spectra, and just wanted to check whether the templates used are in vacuum or air wavelengths?

Thanks!
Tania

**Comment by Samreay** [comment]
Hey Tania! The templates come from a few sources, some of which are atmospheric and some are already in vacuum. Marz will convert to vacuum if it's not already there, and this is controlled by the `shift` property of each template (in templates.js). In general, Marz works in vacuum wavelengths

**Comment by tansb** [comment]
Thanks Sam!
(Also I've just seen that this question was already asked & answered previously, my mistake!)
