### ISSUE TITLE
Recording the best few chisquared fits

### ISSUE THREAD

**Issue by dparkins** [Samreay/Marz#59]
It would be good to see the top 5 (say) chi-squared fits for each spectra, allowing the user to cycle between them

**Comment by Samreay** [comment]
Will put it in.

**Comment by Samreay** [comment]
Closed in 449aa7954a6f8fc0a61c23de55236189aa167d0d. Brings back 7 comparisons, can toggle through with the 'o' key just like runz. Can add more - currently store 1200 of the best results, so 7 is only to make tabbing through them easy.

![image](https://cloud.githubusercontent.com/assets/6748505/3201087/f28efdc0-ed83-11e3-8dc7-75e79a667585.png)
